"use client";

import { useEffect, useState } from "react";
import { apiRequest, display, idOf, keyOf, pick, statusLabel } from "@/controllers/api.controller";
import type { AuthUser, Role, Row } from "@/models/dashboard";
import { PanelHeader } from "@/components/common/PanelHeader";
import { Icon, type IconName } from "@/components/ui/Icon";
import { normalizeTeacherSchedules, teachingState, teachingStateLabel, todaySchedules } from "@/controllers/teaching-schedule.controller";
import type { TeachingSchedule } from "@/models/teaching-schedule";

export function DashboardHome({ role, user, stats, today, token, onNavigate }: { role: Role; user: AuthUser; stats: Record<string, number>; today: string; token: string; onNavigate: (value: string) => void }) {
  const isAdmin = role === "admin";
  const cards: [string, number, IconName, string, string][] = isAdmin ? [
    ["Tổng sinh viên", stats.totalStudents ?? 0, "students", "blue", "Sinh viên"], ["Tổng giảng viên", stats.totalTeachers ?? 0, "teacher", "violet", "Giảng viên"],
    ["Lớp học", stats.totalClasses ?? 0, "class", "green", "Lớp học"], ["Chờ phân công", stats.pendingClassOffers ?? 0, "warning", "orange", "Phân công lớp"],
  ] : [
    ["Lớp phụ trách", stats.classes ?? 0, "class", "blue", "Lớp của tôi"], ["Chờ phản hồi", stats.pendingClassOffers ?? 0, "assign", "violet", "Đề xuất lớp"],
    ["Bài tập", stats.exercises ?? 0, "exercise", "green", "Bài tập"], ["Bài chờ chấm", stats.pendingSubmissions ?? 0, "warning", "orange", "Bài tập"],
  ];
  return <><section className="welcome-row"><div><p className="eyebrow">{today}</p><h1>Chào, {user.fullName || user.username} <span>👋</span></h1><p>{isAdmin ? "Các số liệu dưới đây được lấy trực tiếp từ backend." : "Theo dõi lớp, điểm danh, điểm số và bài tập của bạn."}</p></div><button className="primary-button" onClick={() => onNavigate(isAdmin ? "Sinh viên" : "Điểm danh")}><Icon name={isAdmin ? "userPlus" : "attendance"} size={16} />{isAdmin ? "Tạo sinh viên" : "Điểm danh"}</button></section><section className="stats-grid">{cards.map(([label, value, icon, tone, target]) => <article className="stat-card" key={label}><div className={`stat-icon ${tone}`}><Icon name={icon} size={20} /></div><div className="stat-copy"><p>{label}</p><strong>{new Intl.NumberFormat("vi-VN").format(value)}</strong><small className="up">Dữ liệu hiện tại</small></div><button onClick={() => onNavigate(target)} aria-label={`Mở ${target}`}><Icon name="arrow" size={15} /></button></article>)}</section>{isAdmin ? <AdminOverview token={token} onNavigate={onNavigate} /> : <TeacherOverview token={token} onNavigate={onNavigate} />}</>;
}

function AdminOverview({ token, onNavigate }: { token: string; onNavigate: (value: string) => void }) {
  const [notifications, setNotifications] = useState<Row[]>([]); const [report, setReport] = useState<Row | null>(null);
  useEffect(() => { apiRequest(token, "/notifications").then((p) => setNotifications((p.data || []).slice(0, 5))).catch(() => {}); apiRequest(token, "/statistical-report").then((p) => setReport(p.data || null)).catch(() => {}); }, [token]);
  const quick: [IconName, string, string, string][] = [["userPlus", "Tạo sinh viên", "blue", "Sinh viên"], ["teacher", "Tạo giảng viên", "violet", "Giảng viên"], ["class", "Tạo lớp học", "green", "Lớp học"], ["assign", "Phân công lớp", "orange", "Phân công lớp"]];
  return <div className="dashboard-grid"><section className="panel quick-panel"><PanelHeader title="Truy cập nhanh" sub="Các nghiệp vụ quản trị chính" /><div className="quick-grid">{quick.map(([icon, label, tone, target]) => <button key={label} onClick={() => onNavigate(target)}><span className={tone}><Icon name={icon} size={18} /></span><strong>{label}</strong><small>Mở chức năng →</small></button>)}</div></section><section className="panel status-panel"><PanelHeader title="Tình hình đào tạo" sub="Tổng hợp từ báo cáo thống kê" />{report ? <div className="metric-list"><span>Học phần đang đăng ký <b>{display(keyOf(report, "totalEnrollments"))}</b></span><span>Môn đang hoạt động <b>{display(keyOf(report, "totalCourses"))}</b></span><span>Cảnh báo học vụ <b>{display(keyOf(report, "totalWarnings"))}</b></span><span>Điểm trung bình <b>{display(pick(report, "grades.averageScore"))}</b></span></div> : <p className="empty-note">Chưa tải được báo cáo.</p>}</section><section className="panel activity-panel"><PanelHeader title="Thông báo gần đây" sub="Dữ liệu thực từ hệ thống" /><div className="activity-list">{notifications.length === 0 ? <p className="empty-note">Chưa có thông báo.</p> : notifications.map((item) => <div className="activity" key={idOf(item)}><span className="avatar blue"><Icon name="mail" size={16} /></span><div><strong>{display(keyOf(item, "Subject"))}</strong><p>{display(keyOf(item, "RecipientEmail"))}</p></div><time>{statusLabel(keyOf(item, "Status"))}</time></div>)}</div></section><section className="panel status-panel"><PanelHeader title="Các bước tiếp theo" sub="Không dùng số liệu demo" /><div className="status-ok"><span><Icon name="check" size={17} /></span><div><strong>Dashboard đã kết nối API</strong><p>Thao tác trên các trang chức năng sẽ ghi trực tiếp vào backend.</p></div></div><button className="secondary-wide" onClick={() => onNavigate("Báo cáo")}>Xem báo cáo đầy đủ →</button></section></div>;
}

function TeacherOverview({ token, onNavigate }: { token: string; onNavigate: (value: string) => void }) {
  const [schedules, setSchedules] = useState<TeachingSchedule[]>([]); const [exercises, setExercises] = useState<Row[]>([]); const [offers, setOffers] = useState<Row[]>([]);
  useEffect(() => { Promise.all([apiRequest(token, "/teacher/schedule"), apiRequest(token, "/exercises"), apiRequest(token, "/class-offers")]).then(([s, e, o]) => { setSchedules(normalizeTeacherSchedules(s)); setExercises((Array.isArray(e.data) ? e.data : []).slice(0, 5) as Row[]); setOffers((Array.isArray(o.data) ? o.data : []).filter((x: Row) => String(keyOf(x, "Status")).toLowerCase() === "pending").slice(0, 5)); }).catch(() => {}); }, [token]);
  const now = new Date(); const today = todaySchedules(schedules, now);
  const actions: [IconName, string, string, string, string][] = [["calendar", "Lịch dạy", `${today.length} lịch trong hôm nay`, "violet", "Lịch dạy"], ["attendance", "Điểm danh", "Tạo phiên và quản lý chuyên cần", "blue", "Điểm danh"], ["grade", "Bảng điểm", "Nhập và duyệt điểm", "green", "Bảng điểm"], ["exercise", "Bài tập", "Tạo, xem bài nộp, chấm bài", "orange", "Bài tập"], ["assign", "Đề xuất lớp", `${offers.length} đề xuất đang chờ`, "violet", "Đề xuất lớp"]];
  return <div className="dashboard-grid teacher-grid"><section className="panel schedule-panel"><PanelHeader title="Lịch dạy hôm nay" sub="Lớp, môn, phòng và giờ dạy" />{today.length === 0 ? <div className="empty-schedule"><p className="empty-note">Hôm nay không có lịch dạy.</p><button onClick={() => onNavigate("Lịch dạy")}>Xem lịch cả tuần →</button></div> : <div className="class-list">{today.slice(0, 5).map((item) => { const state = teachingState(item, now); return <button className="class-row" key={item.id} onClick={() => onNavigate("Lịch dạy")}><span className="class-time blue">{item.startTime}<small>{item.endTime}</small></span><span className="class-info"><i className={state === "current" ? "green" : "blue"} /><span><strong>{item.classCode} · {item.courseName}</strong><small>{item.roomName} · {item.session} · <em className={`inline-state ${state}`}>{teachingStateLabel(state)}</em></small></span></span><b>›</b></button>; })}</div>}</section><section className="panel quick-panel"><PanelHeader title="Công việc giảng dạy" sub="Thao tác thường dùng" /><div className="teacher-actions">{actions.map(([icon, title, sub, tone, target]) => <button key={title} onClick={() => onNavigate(target)}><span className={tone}><Icon name={icon} size={18} /></span><span><strong>{title}</strong><small>{sub}</small></span><b>›</b></button>)}</div></section><section className="panel submissions-panel"><PanelHeader title="Bài tập gần đây" sub="Theo hạn nộp" />{exercises.length === 0 ? <p className="empty-note">Chưa có bài tập.</p> : exercises.map((row) => <div className="submission" key={idOf(row)}><span className="file-icon blue"><Icon name="exercise" size={16} /></span><div><strong>{display(keyOf(row, "Title"))}</strong><p>{display(pick(row, "Class.ClassCode"))}</p></div><time>{display(keyOf(row, "DueDate"))}</time></div>)}</section><section className="panel status-panel"><PanelHeader title="Đề xuất lớp chờ phản hồi" sub="Cần xử lý" />{offers.length === 0 ? <div className="status-ok"><span><Icon name="check" size={17} /></span><div><strong>Không có đề xuất đang chờ</strong><p>Bạn đã xử lý hết.</p></div></div> : offers.map((row) => <button className="offer-mini" key={idOf(row)} onClick={() => onNavigate("Đề xuất lớp")}><strong>{display(pick(row, "Class.ClassCode"))}</strong><span>{display(keyOf(row, "Message"))}</span></button>)}</section></div>;
}
