"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */

import { useEffect, useState } from "react";
import { apiRequest, display, keyOf } from "@/controllers/api.controller";
import type { Role, Row } from "@/models/dashboard";
import { PanelHeader } from "@/components/common/PanelHeader";
import { Icon } from "@/components/ui/Icon";

export function ReportPage({ role, token }: { role: Role; token: string }) {
  const [data, setData] = useState<Row | null>(null); const [error, setError] = useState(""); const [exporting, setExporting] = useState(false);
  const load = async () => { try { const p = await apiRequest(token, "/statistical-report"); setData(p.data || null); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Không tải được báo cáo"); } };
  useEffect(() => { load(); }, [token]);
  const exportTranscript = async () => { setExporting(true); try { const response = await apiRequest(token, "/transcripts/export?format=csv"); if (!(response instanceof Response)) return; const blob = await response.blob(); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `transcript-${new Date().toISOString().slice(0, 10)}.csv`; a.click(); URL.revokeObjectURL(url); } catch (e) { setError(e instanceof Error ? e.message : "Không xuất được file"); } finally { setExporting(false); } };
  const attendance = (keyOf(data || {}, "attendance") || {}) as Row; const grades = (keyOf(data || {}, "grades") || {}) as Row;
  const primary = role === "admin" ? [["Sinh viên", keyOf(data || {}, "totalStudents")], ["Giảng viên", keyOf(data || {}, "totalTeachers")], ["Lớp", keyOf(data || {}, "totalClasses")], ["Môn học", keyOf(data || {}, "totalCourses")], ["Đăng ký học phần", keyOf(data || {}, "totalEnrollments")], ["Cảnh báo", keyOf(data || {}, "totalWarnings")]] : [["Lớp", keyOf(data || {}, "totalClasses")], ["Sinh viên/lượt đăng ký", keyOf(data || {}, "totalEnrollments")], ["Bài tập", keyOf(data || {}, "totalExercises")], ["Bài nộp", keyOf(data || {}, "totalSubmissions")]];
  return <section className="feature-page"><div className="feature-heading"><div><p className="eyebrow">Tổng hợp trực tiếp từ cơ sở dữ liệu</p><h1>Báo cáo</h1><p>Số liệu chuyên cần, điểm số và quy mô đào tạo.</p></div><div className="form-actions"><button className="refresh-button" onClick={load}><Icon name="refresh" size={15} />Làm mới</button>{role === "teacher" && <button className="primary-button" disabled={exporting} onClick={exportTranscript}><Icon name="upload" size={15} />{exporting ? "Đang xuất..." : "Xuất transcript CSV"}</button>}</div></div>{error && <div className="feature-error">! {error}</div>}{!data ? <div className="panel"><p className="empty-note">Đang tải báo cáo...</p></div> : <><div className="report-cards">{primary.map(([label, value]) => <article key={String(label)}><span>{String(label)}</span><strong>{new Intl.NumberFormat("vi-VN").format(Number(value || 0))}</strong></article>)}</div><div className="report-grid"><section className="panel"><PanelHeader title="Chuyên cần" sub="Theo trạng thái" /><div className="metric-list"><span>Có mặt <b>{display(keyOf(attendance, "present"))}</b></span><span>Vắng <b>{display(keyOf(attendance, "absent"))}</b></span><span>Đi trễ <b>{display(keyOf(attendance, "late"))}</b></span><span>Có phép <b>{display(keyOf(attendance, "excused"))}</b></span></div></section><section className="panel"><PanelHeader title="Kết quả điểm" sub="Điểm đã nhập trong hệ thống" /><div className="metric-list"><span>Tổng bản ghi điểm <b>{display(keyOf(grades, "totalGrades"))}</b></span><span>Điểm trung bình <b>{display(keyOf(grades, "averageScore"))}</b></span><span>Đã duyệt <b>{display(keyOf(grades, "approved"))}</b></span><span>Bản nháp <b>{display(keyOf(grades, "draft"))}</b></span></div></section></div></>}</section>;
}
